In [3]:
import pandas as pd
import numpy as np

# CSV-Datei direkt laden
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"
df = pd.read_csv(url)
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [1]:
import pandas as pd
import numpy as np

# CSV-Datei direkt laden
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"
df = pd.read_csv(url)
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
# Q1: Pandas Version
print("Q1 Pandas Version:", pd.__version__)

# Q2: Anzahl der Datensätze
print("Q2 Records count:", len(df))

# Q3: Anzahl der Kraftstoffarten
print("Q3 Fuel types:", df['fuel_type'].nunique())

# Q4: Spalten mit fehlenden Werten
print("Q4 Columns with missing values:", (df.isnull().sum() > 0).sum())

# Q5: Maximale Effizienz (Asien)
print("Q5 Max fuel efficiency (Asia):", df[df['origin'] == 'Asia']['fuel_efficiency'].max())

Q1 Pandas Version: 3.0.5
Q2 Records count: 10000
Q3 Fuel types: 3
Q4 Columns with missing values: 2

KeyError: 'fuel_efficiency'

In [5]:
orig_median = df['horsepower'].median()
mode_hp = df['horsepower'].mode()[0]

df_filled = df.copy()
df_filled['horsepower'] = df_filled['horsepower'].fillna(mode_hp)
new_median = df_filled['horsepower'].median()

print(f"Q6 - Originaler Median: {orig_median}")
print(f"Q6 - Häufigster Wert (Modus): {mode_hp}")
print(f"Q6 - Neuer Median: {new_median}")

if new_median > orig_median:
    print("Q6 Antwort: Yes, it increased")
elif new_median < orig_median:
    print("Q6 Antwort: Yes, it decreased")
else:
    print("Q6 Antwort: No")

Q6 - Originaler Median: 254.0
Q6 - Häufigster Wert (Modus): 252.0
Q6 - Neuer Median: 252.0
Q6 Antwort: Yes, it decreased

In [6]:
# Filtern & erste 7 Zeilen als Array X
asia_df = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
X = asia_df.head(7).to_numpy()

# Normalgleichung: w = (X^T * X)^(-1) * X^T * y
XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = (XTX_inv @ X.T) @ y

print("Q7 Sum of weights:", w.sum())

Q7 Sum of weights: 0.36919696904925486